name: deadsnakes
description: install (pre-release) pythons from deadsnakes
inputs:
  python-version:
    description: python version to use, such as '3.9'
    required: true
  debug:
    description: use debug version of python
    required: false
    default: false
  nogil:
    description: use free-threaded version of python
    required: false
    default: false
  tk:
    description: include Tkinter
    required: false
    default: false
runs:
  using: composite
  steps:
  - name: add deadsnakes ppa and install ${{ inputs.python-version }} ${{ inputs.debug == 'true' && '(debug)' || '' }} ${{ inputs.tk == 'true' && '(tk)' || '' }}
    run: ${{ github.action_path }}/bin/install-python ${{ inputs.python-version }} ${{ inputs.debug == 'true' && '--debug' || '' }} ${{ inputs.nogil == 'true' && '--nogil' || '' }} ${{ inputs.tk == 'true' && '--tk' || '' }}
    shell: bash
