on:
  pull_request:
  push:
    branches: [main, test-me-*]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - {python: '3.7', debug: true, nogil: false}
        - {python: '3.13-dev', debug: false, nogil: false}
        - {python: '3.14-dev', debug: false, nogil: true}
        - {python: '3.14-dev', debug: false, nogil: false, tk: true}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.
      with:
        python-version: ${{ matrix.python }}
        debug: ${{ matrix.debug }}
        nogil: ${{ matrix.nogil }}
        tk: ${{ matrix.tk }}

    - name: check tk
      if: matrix.tk
      run: python -c 'import tkinter'
